name: "Google Spreadsheet to CSV Downloader"
description: "Downloads a Google Spreadsheet and exports it as a CSV file."
inputs:
  service_account_json_path:
    description: "GCE Service Account Json Path"
    required: true
  spreadsheet_file_id:
    description: Google Spreadsheet file ID to download.
    required: true
  destination:
    description: Destination file path to save the CSV file.
    required: true
runs:
  using: composite
  steps:
    - name: Download spreadsheet and convert to CSV
      env:
        SERVICE_ACCOUNT_JSON_PATH: ${{ inputs.service_account_json_path }}
        QUERY: ${{ inputs.query }}
        DESTINATION: ${{ inputs.destination }}
      run: |
        node -e "
          const { google } = require('googleapis');
          const fs = require('fs');
          const auth = new google.auth.GoogleAuth({
            keyFile: '${{ inputs.service_account_json_path }}',
            scopes: ['https://www.googleapis.com/auth/drive.readonly'],
          });
          const drive = google.drive({ version: 'v3', auth });
          const fileId = '${{ inputs.spreadsheet_file_id }}';
          const dest = fs.createWriteStream('${{ inputs.destination }}');
          drive.files.export({ fileId, mimeType: 'text/csv' }, { responseType: 'stream' },
            (err, { data }) => {
              if (err) throw err;
              data.pipe(dest);
            }
          );
        "
