name: Update Images from Google Drive

on:
  repository_dispatch:
    types: [on-demand-upload-images]

jobs:
  update-images:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT_TOKEN }}

    # Node.jsをセットアップ
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    # 必要なパッケージをインストール
    - name: Install dependencies
      run: |
        npm install googleapis

    # Google Driveから画像をダウンロード
    - name: Download files from Google Drive
      uses: tp-jp/gdrive-file-downloader@main
      with:
        google_client_id: ${{ secrets.GOOGLE_CLIENT_ID }}
        google_client_secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        google_refresh_token: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
        file_ids: '[{ id: "157EXW6averB9f5omYVGqa19UHp0Hr8eJ", name: "OuraiWorld/Poster01.png" }, { id: "1ZEnw6zHG9_hoVtEXu-6V_RwTU3gL8zX-", name: "OuraiWorld/Poster02.png" }, { id: "1gEgzkHV3rwkq9piExV3sN01wCJD-dwi-", name: "OuraiWorld/Poster03.png" }, { id: "1gSqdvTKzpZLx47SWwOzNF76XCDrjzdO8", name: "OuraiWorld/Poster04.png" }]'

    - name: Check for changes
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"

        git add --all
        git reset -- package.json package-lock.json node_modules/

        if ! git diff-index --quiet HEAD --; then
          git commit -m "Update images from Google Drive"
          git push
        else
          echo "No changes to commit."
        fi
